# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: marianferenc/graphql_router_service
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: golang
  type: NodePort
  externalPort: 4000
  internalPort: 4000
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
env:
  prismaEndpoint: "http://prisma:4466"
ingress:
  enabled: false
