[environments]
  [environments.development]
    name = "meetings_service"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
    registry = "marianferenc"
