# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: marianferenc/meetings_service
service:
  name: meetings-service
  type: NodePort
  externalPort: 8092
  internalPort: 8092
ingress:
  enabled: false
